# Generated by Django 5.0.7 on 2024-07-25 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 14, 37, 24, 96822, tzinfo=datetime.timezone.utc)),
        ),
    ]
